// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_maKzFsRz__CeEUUfOzXg7vCwifd1H9c',
    appId: '1:869179046649:web:a0a5829f2f29a70a048028',
    messagingSenderId: '869179046649',
    projectId: 'bobby-shopping',
    authDomain: 'bobby-shopping.firebaseapp.com',
    storageBucket: 'bobby-shopping.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJGvDx_eQaCn82PThlzMsM65_Fpx2jWgc',
    appId: '1:869179046649:android:c21fc34032c999cf048028',
    messagingSenderId: '869179046649',
    projectId: 'bobby-shopping',
    storageBucket: 'bobby-shopping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa9gsR6AASaDvhMkz24-OnVqVn8P6PWAk',
    appId: '1:869179046649:ios:b5f508cf55f5f02a048028',
    messagingSenderId: '869179046649',
    projectId: 'bobby-shopping',
    storageBucket: 'bobby-shopping.appspot.com',
    iosClientId: '869179046649-q98kithdptc9gmh7v45ftcghukeh1ens.apps.googleusercontent.com',
    iosBundleId: 'com.example.bobbyShopping',
  );
}
